package utn.back.mordiscoapi.enums;

public enum TipoNotificacion {
    NUEVO_PEDIDO,
    PEDIDO_EN_PREPARACION,
    PEDIDO_LISTO_PARA_ENTREGAR,
    PEDIDO_LISTO_PARA_RETIRAR,
    PEDIDO_EN_CAMINO,
    PEDIDO_COMPLETADO,
    PEDIDO_CANCELADO,
    PAGO_CONFIRMADO,
    PAGO_RECHAZADO
}
